// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDADfl5P0WDvD3C7yU7h2Gic7psHyH0LJY',
    appId: '1:821295791396:web:ba42b509cb91b162a547b1',
    messagingSenderId: '821295791396',
    projectId: 'udemysnsapplication0103',
    authDomain: 'udemysnsapplication0103.firebaseapp.com',
    storageBucket: 'udemysnsapplication0103.appspot.com',
    measurementId: 'G-34EEFV8Q9X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1-H_-ePhu_LWQEQsYeQllJvpMkFsHXuQ',
    appId: '1:821295791396:android:f24968581af895dda547b1',
    messagingSenderId: '821295791396',
    projectId: 'udemysnsapplication0103',
    storageBucket: 'udemysnsapplication0103.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEIIUgNhUqYQgPoLaUToy85Z4jAa2PawU',
    appId: '1:821295791396:ios:5146fa7589fcd82ca547b1',
    messagingSenderId: '821295791396',
    projectId: 'udemysnsapplication0103',
    storageBucket: 'udemysnsapplication0103.appspot.com',
    iosClientId: '821295791396-s3tf2a0h12ik78j8u7au1kv7mq9vd9p4.apps.googleusercontent.com',
    iosBundleId: 'com.example.udemypractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEIIUgNhUqYQgPoLaUToy85Z4jAa2PawU',
    appId: '1:821295791396:ios:5146fa7589fcd82ca547b1',
    messagingSenderId: '821295791396',
    projectId: 'udemysnsapplication0103',
    storageBucket: 'udemysnsapplication0103.appspot.com',
    iosClientId: '821295791396-s3tf2a0h12ik78j8u7au1kv7mq9vd9p4.apps.googleusercontent.com',
    iosBundleId: 'com.example.udemypractice',
  );
}
